### ISSUE TITLE
Use vscode panel border color for table header box shadow

### ISSUE THREAD

**Issue by usernamehw** [RandomFractals/vscode-data-table#52]
![Screenshot (148)](https://user-images.githubusercontent.com/9638156/126836108-d5ee2ad6-c063-4c63-9c26-d42c476a2a3f.png)

```css
.oi-f09d35-table thead th {
    box-shadow: 0 1px 0 #ccc;
}
```
